// Package sshconf はisuenv環境向けのssh config生成を提供する。
package sshconf

import (
	"errors"
	"fmt"
	"os"
	"strings"
)

type Host struct {
	Alias        string
	HostName     string
	User         string
	IdentityFile string
}

// Render は練習環境用のssh config断片を生成する。
// 環境は使い捨てでIPが再利用されるためホストキー検証は無効化する。
func Render(hosts []Host) string {
	var b strings.Builder
	b.WriteString("# Generated by isuenv. DO NOT EDIT.\n")
	for _, h := range hosts {
		fmt.Fprintf(&b, "\nHost %s\n  HostName %s\n  User %s\n  IdentityFile %s\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n",
			h.Alias, h.HostName, h.User, h.IdentityFile)
	}
	return b.String()
}

func WriteConfig(path string, hosts []Host) error {
	return os.WriteFile(path, []byte(Render(hosts)), 0o600)
}

// EnsureInclude は configPath の先頭に Include 行を一度だけ追加する。
func EnsureInclude(configPath, includePath string) error {
	line := "Include " + includePath
	data, err := os.ReadFile(configPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if strings.Contains(string(data), line) {
		return nil
	}
	content := line + "\n" + string(data)
	return os.WriteFile(configPath, []byte(content), 0o600)
}
