package cmd

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	ec2types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/kyosu-1/isuenv/internal/awsapi"
	"github.com/kyosu-1/isuenv/internal/engine"
)

// fakeHome は $HOME を差し替えて .ssh ディレクトリを用意し、生成されたssh configを読む関数を返す。
func fakeHome(t *testing.T) func() string {
	t.Helper()
	home := t.TempDir()
	if err := os.Mkdir(filepath.Join(home, ".ssh"), 0o700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("HOME", home)
	return func() string {
		t.Helper()
		data, err := os.ReadFile(filepath.Join(home, ".ssh", "isuenv_config"))
		if err != nil {
			t.Fatal(err)
		}
		return string(data)
	}
}

func instance(id, env string, node int, publicIP string) ec2types.Instance {
	return ec2types.Instance{
		InstanceId:      aws.String(id),
		PublicIpAddress: aws.String(publicIP),
		InstanceType:    ec2types.InstanceTypeC5Large,
		Tags: []ec2types.Tag{
			{Key: aws.String(engine.TagManaged), Value: aws.String("true")},
			{Key: aws.String(engine.TagEnv), Value: aws.String(env)},
			{Key: aws.String(engine.TagNode), Value: aws.String(strconv.Itoa(node))},
		},
	}
}

func describing(instances ...ec2types.Instance) func(context.Context, *ec2.DescribeInstancesInput) (*ec2.DescribeInstancesOutput, error) {
	return func(context.Context, *ec2.DescribeInstancesInput) (*ec2.DescribeInstancesOutput, error) {
		return &ec2.DescribeInstancesOutput{Reservations: []ec2types.Reservation{{Instances: instances}}}, nil
	}
}

// terminate直後のDescribeInstancesは結果整合性により対象をまだrunningとして返すことがある。
// その結果をそのまま書き出すと、消したはずのホストがssh configに残ってしまう。
func TestRefreshSSHConfigSkipsExcludedInstances(t *testing.T) {
	readConfig := fakeHome(t)
	e := &engine.Engine{EC2: &awsapi.Mock{
		DescribeInstancesFunc: describing(
			instance("i-1", "isucon13", 1, "203.0.113.1"),
			instance("i-2", "isucon13", 2, "203.0.113.2"),
		),
	}}

	if err := refreshSSHConfig(context.Background(), e, "i-2"); err != nil {
		t.Fatal(err)
	}

	got := readConfig()
	if !strings.Contains(got, "Host isucon13-1") {
		t.Errorf("残っているノードのエントリが必要:\n%s", got)
	}
	if strings.Contains(got, "isucon13-2") || strings.Contains(got, "203.0.113.2") {
		t.Errorf("terminate済みノードのエントリが残っている:\n%s", got)
	}
}

func TestRunDownRemovesTerminatedHostsFromSSHConfig(t *testing.T) {
	readConfig := fakeHome(t)
	var terminated []string
	e := &engine.Engine{EC2: &awsapi.Mock{
		DescribeInstancesFunc: describing(instance("i-1", "isucon14", 1, "203.0.113.10")),
		TerminateInstancesFunc: func(_ context.Context, in *ec2.TerminateInstancesInput) (*ec2.TerminateInstancesOutput, error) {
			terminated = in.InstanceIds
			return &ec2.TerminateInstancesOutput{}, nil
		},
	}}

	var out bytes.Buffer
	if err := runDown(context.Background(), e, "isucon14", &out); err != nil {
		t.Fatal(err)
	}

	if len(terminated) != 1 || terminated[0] != "i-1" {
		t.Fatalf("terminate対象が想定と違う: %v", terminated)
	}
	if !strings.Contains(out.String(), "Terminating isucon14") {
		t.Errorf("terminate対象を報告していない: %q", out.String())
	}
	if got := readConfig(); strings.Contains(got, "isucon14-1") {
		t.Errorf("terminate済みホストがssh configに残っている:\n%s", got)
	}
}

// 環境がすでに無い場合でも、前回のdownで残った古いエントリを回収できるようにする。
func TestRunDownRefreshesSSHConfigWhenNothingToTerminate(t *testing.T) {
	readConfig := fakeHome(t)
	stale := filepath.Join(os.Getenv("HOME"), ".ssh", "isuenv_config")
	if err := os.WriteFile(stale, []byte("# Generated by isuenv. DO NOT EDIT.\n\nHost isucon14-1\n  HostName 203.0.113.10\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	e := &engine.Engine{EC2: &awsapi.Mock{DescribeInstancesFunc: describing()}}

	var out bytes.Buffer
	if err := runDown(context.Background(), e, "isucon14", &out); err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(out.String(), "Nothing to do") {
		t.Errorf("対象なしを報告していない: %q", out.String())
	}
	if got := readConfig(); strings.Contains(got, "isucon14-1") {
		t.Errorf("古いエントリが残っている:\n%s", got)
	}
}
